In [ ]:
19, 18, 21],
    [30, 28, 27, 29, 31],
    [25, 24, 26, 23, 22]
])

normalized = np.zeros((4, 5))

normalized[:,0] = sensor_data[:,0]/np.max(sensor_data, axis=0)[0]
normalized[:,1] = sensor_data[:,1]/np.max(sensor_data, axis=0)[1]
normalized[:,2] = sensor_data[:,2]/np.max(sensor_data, axis=0)[2]
normalized[:,3] = sensor_data[:,3]/np.max(sensor_data, axis=0)[3]
normalized[:,4]= sensor_data[:,4]/np.max(sensor_data, axis=0)[4]
print(normalized)import numpy as np

sensor_data = np.array([
    [12, 15, 14, 10, 13],
    [20, 22, 19, 18, 21],
    [30, 28, 27, 29, 31],
    [25, 24, 26, 23, 22]
])
print("Mean per machine:", np.mean(sensor_data, axis=1))
print("Maximum reading per time interval:", np.max(sensor_data, axis=0))
sensor_data = np.array([
    [12, 15, 14, 10, 13],
    [20, 22, 

Mean per machine: [12.8 20.  29.  24. ]
Maximum reading per time interval: [30 28 27 29 31]
[[0.4        0.53571429 0.51851852 0.34482759 0.41935484]
 [0.66666667 0.78571429 0.7037037  0.62068966 0.67741935]
 [1.         1.         1.         1.         1.        ]
 [0.83333333 0.85714286 0.96296296 0.79310345 0.70967742]]


In [26]:
import numpy as np

sensor_data = np.array([
    [12, 15, 14, 10, 13],
    [20, 22, 19, 18, 21],
    [30, 28, 27, 29, 31],
    [25, 24, 26, 23, 22]
])

mean = np.mean(sensor_data, axis=1)
print("Mean per machine:", np.mean(sensor_data, axis=1))

max_values = np.max(sensor_data, axis=0)
print("Maximum reading per time interval:", max_values)

normalized = sensor_data / max_values
print("Normalized Data:\n", normalized)

machines_above_20 = np.where(mean > 20)[0]
print("Machines with mean above 20:", machines_above_20)

reshaped = sensor_data.reshape(2, 10)
print("Reshaped Matrix (2,10):\n", reshaped)


Mean per machine: [12.8 20.  29.  24. ]
Maximum reading per time interval: [30 28 27 29 31]
Normalized Data:
 [[0.4        0.53571429 0.51851852 0.34482759 0.41935484]
 [0.66666667 0.78571429 0.7037037  0.62068966 0.67741935]
 [1.         1.         1.         1.         1.        ]
 [0.83333333 0.85714286 0.96296296 0.79310345 0.70967742]]
Machines with mean above 20: [2 3]
Reshaped Matrix (2,10):
 [[12 15 14 10 13 20 22 19 18 21]
 [30 28 27 29 31 25 24 26 23 22]]


In [29]:
import numpy as np
matrix1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
matrix2 = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)

result = np.dot(matrix1, matrix2)
print("\nMatrix Multiplication Result:")
print(result)

elementwise_result = matrix1 * matrix2
print("\nElement-wise Multiplication Result:")
print(elementwise_result)

greater_than_100 = result[result > 100]
print("\nElements greater than 100:")
print(greater_than_100)

matrix1[matrix1 < 10] = 0
matrix2[matrix2 < 10] = 0
print("Matrix 1 after replacement:")
print(matrix1)

print("\nMatrix 2 after replacement:")
print(matrix2)

stacked_matrix = np.vstack((matrix1, matrix2))
print("Vertically Stacked Matrix:")
print(stacked_matrix)


Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Multiplication Result:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise Multiplication Result:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Elements greater than 100:
[138 114]
Matrix 1 after replacement:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Matrix 2 after replacement:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Vertically Stacked Matrix:
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
